/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XnHlpv9yth9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function CalendarRelatory() {
  return (
    <div>
      <div className="w-full max-w-2xl">
        <div>
          <div>Weekly Training Schedule</div>
          <div>Enter your name or nickname for each day of the week.</div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-7 gap-4 p-4">
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Sunday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Monday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Tuesday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Wednesday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Thursday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Friday</div>
            <Input placeholder="Your name" />
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="font-medium">Saturday</div>
            <Input placeholder="Your name" />
          </div>
        </div>
        <div className="flex justify-end gap-2">
          <Button variant="outline">Cancel</Button>
          <Button>Save</Button>
        </div>
      </div>
    </div>
  )
}
